services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  front:
    build: ./front
    ports:
      - 80:80
    restart: always

  app:
    build: .
    restart: always
    env_file: .env

volumes:
  pgdata:
    driver: local
